# Python requirements
FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel

RUN pip3 install \
        theano==1.0.5 \
        Cython==0.29.30 \
        numpy==1.24.4 \
        torch==1.11.0 \
        pillow==10.4.0 \
        transformers==4.19.2
